development:
  adapter: mysql
  encoding: utf8
  database: singles_development
  username: singles    
  password: mauisun6
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: singles_test
  username: singles
  password: mauisun6
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: singles_production
  username: singles
  password: mauisun6
  host: localhost
